In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
from xml.etree import ElementTree
import glob

In [3]:
files = glob.glob('/tmp/html/*_index.html')

null_path = '/tmp/html/null.html'

out_path = '/tmp/html/index.html'

pattern = '<!-- {MESHES} -->'

with open(null_path,'r') as f:
    null = f.read()
    

In [4]:
html_string = lambda s: ElementTree.tostring(s, method='html')


In [6]:
shapes = []

for f in files:
    shapes += ElementTree.parse(f).getroot().findall('.//group/transform/*')
        
grouptext = [html_string(shape) for shape in shapes]
html_content = ''.join(grouptext)
null = null.replace(pattern, html_content)

with open(out_path, 'w') as f:
    f.write(null)

In [7]:
import cv2

In [13]:
a = cv2.imread('/tmp/a.png', 0)

In [14]:
a.shape

(1024, 1024)

In [15]:
a[0,0]

140

In [16]:
import numpy as np

In [19]:
np.uint64((1,2,3))

array([1, 2, 3], dtype=uint64)

In [20]:
np.array((1,2,3), dtype=np.uint32)

array([1, 2, 3], dtype=uint32)

In [22]:
2 ** np.uint32((1,2,3))

array([2, 4, 8], dtype=uint32)